-- Script to manually create the GeneratedBarcodes table
-- This should be run if the migration fails

CREATE TABLE "GeneratedBarcodes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RollAssignmentId" integer NOT NULL,
    "Barcode" text NOT NULL,
    "RollNumber" integer NOT NULL,
    "GeneratedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_GeneratedBarcodes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GeneratedBarcodes_RollAssignments_RollAssignmentId" 
        FOREIGN KEY ("RollAssignmentId") 
        REFERENCES "RollAssignments" ("Id") 
        ON DELETE CASCADE
);

CREATE INDEX "IX_GeneratedBarcodes_RollAssignmentId" 
    ON "GeneratedBarcodes" ("RollAssignmentId");

-- Add the migration to the history table so EF Core knows it's been applied
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251003094500_AddGeneratedBarcodesTable', '8.0.8');